#!/usr/bin/env bash
# Fetch the CC0 photo sources the texture generator reads (tools/art/textures.py).
#
# Intake rule (intake/README.md): raw sources land in intake/_sources/ untouched,
# pinned to an exact commit so the committed textures can be regenerated byte for
# byte, and their provenance is recorded per texture in content/art/textures/index.json.
# intake/_sources/ is gitignored: we commit what we made, not what we downloaded.
#
# mini_textures bundles 12 ambientCG sets (CC0 1.0) and 38 sets made by the
# addon's author (declared CC0 1.0 in its README).
set -euo pipefail

REPO_URL="https://github.com/amazingsammed/mini_textures"
COMMIT="b080ca4df63813b3b764a8f31b3f418e3d6b6a2a"   # main, 2026-09-29

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
dest="$root/intake/_sources/mini_textures"

if [ -d "$dest/.git" ] && [ "$(git -C "$dest" rev-parse HEAD 2>/dev/null)" = "$COMMIT" ]; then
    echo "mini_textures already at $COMMIT"
    exit 0
fi

rm -rf "$dest"
mkdir -p "$(dirname "$dest")"
# A shallow fetch of the one pinned commit: no history we don't need.
git init -q "$dest"
git -C "$dest" remote add origin "$REPO_URL"
git -C "$dest" fetch -q --depth 1 origin "$COMMIT"
git -C "$dest" checkout -q --detach FETCH_HEAD
echo "mini_textures fetched at $COMMIT into ${dest#$root/}"
