#!/usr/bin/env python3
"""Tonight's build (ARCHITECTURE §8 note 523): main with the open pull requests on top, and a test plan from what they say.

Every open pull request against main that isn't a draft, whose head's checks are all green and that merges cleanly is
merged onto main, in number order. One that conflicts (with main, or with one merged before it) is left out and listed with
why, as is one that's red, still running, a draft or based on another branch. The test plan names each merged pull request,
its link and its "how to check" lines: the body's Verified / How to check / Test plan section (and its kin: Tests, Local
checks), else its first paragraph. D1 did this by hand for the director's test builds; this does it every night.

    python3 tools/tonight/integrate.py --repo nsmith-gd/darkterritory [--base main] [--out out/tonight] [--run URL]

runs in a checkout of the base (.github/workflows/tonight.yml), merges there, and writes out/tonight/TEST-PLAN.md and
tonight.json; the workflow builds the result and force-pushes it to the `tonight` branch. The pull requests and their heads'
checks are read with `gh api` (REST, which the cloud sessions' proxy passes as well as Actions does; it refuses GraphQL, so
not `gh pr list --json`). `--dry-run` reads and chooses but merges nothing (the plan lists what would be merged).

    python3 tools/tonight/integrate.py --offline-test

checks it without the network: the choosing and the test plans against tools/tonight/fixture.json (pull requests as
read_prs gives them, bodies from the repository's own), and the merging in a scratch repository of its own (a clean one
merged; one that conflicts with one merged before it, and one that conflicts with main, left out with why).
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = 100

# A check that ran and came out like this is green; anything else that's finished is red.
GREEN = {"SUCCESS", "NEUTRAL", "SKIPPED"}

# The sections a body says how to check it in, by their heading's start (lower case). The repository has no pull request
# template: bodies say "## Verified", "**How to check**", "## Test plan", "## Tests", "## Local checks, after merging main".
PLAN_HEADINGS = ("how to check", "how to test", "how to verify", "how to see", "test plan", "testing", "tested", "verified",
                 "verification", "local checks", "checks", "tests", "to check")

# The lines every agent's body ends with: never a test plan's.
FOOTER = re.compile(r"^(\U0001F916 Generated with|https://claude\.ai/code/|_Generated by|---\s*$)")
ATX = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
BOLD_LINE = re.compile(r"^\*\*([^*].*?)\*\*\s*:?\s*$")
BOLD_LABEL = re.compile(r"^\*\*([^*]+?)\*\*\s*:?\s*(\S.*)$")


def run(args, cwd=None, check=True):
    p = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if check and p.returncode != 0:
        raise RuntimeError(f"{' '.join(args)}: {p.stderr.strip() or p.stdout.strip()}")
    return p


# ---- reading ----------------------------------------------------------------------------------------------------------

def gh(path):
    return json.loads(run(["gh", "api", path]).stdout or "null")


def read_prs(repo, base):
    """The open pull requests, each with its head's checks (only for those that could be chosen: not drafts, on the base)."""
    prs, page = [], 1
    while True:
        batch = gh(f"repos/{repo}/pulls?state=open&per_page={PAGE}&page={page}") or []
        for p in batch:
            pr = {"number": p["number"], "title": p["title"], "url": p["html_url"], "isDraft": bool(p.get("draft")),
                  "baseRefName": p["base"]["ref"], "headRefName": p["head"]["ref"], "headRefOid": p["head"]["sha"],
                  "body": p.get("body") or "", "author": {"login": (p.get("user") or {}).get("login")}, "statusCheckRollup": []}
            if not pr["isDraft"] and pr["baseRefName"] == base:
                pr["statusCheckRollup"] = head_checks(repo, pr["headRefOid"])
            prs.append(pr)
        if len(batch) < PAGE:
            return prs
        page += 1


def head_checks(repo, sha):
    """A commit's checks: its check runs (each name's latest) and its commit statuses."""
    found, page = [], 1
    while True:
        runs = (gh(f"repos/{repo}/commits/{sha}/check-runs?per_page={PAGE}&page={page}") or {}).get("check_runs", [])
        found += [{"__typename": "CheckRun", "name": c.get("name"), "status": (c.get("status") or "").upper(),
                   "conclusion": (c.get("conclusion") or "").upper()} for c in runs]
        if len(runs) < PAGE:
            break
        page += 1
    statuses = (gh(f"repos/{repo}/commits/{sha}/status") or {}).get("statuses", [])
    return found + [{"__typename": "StatusContext", "context": s.get("context"), "state": (s.get("state") or "").upper()} for s in statuses]


# ---- choosing ---------------------------------------------------------------------------------------------------------

def checks(rollup):
    """Whether a head's checks are all green, and if not, why: which are red, which still running, or that none ran."""
    if not rollup:
        return False, "no checks have run on its head (GitHub runs none on a pull request in conflict with its base)"
    red, waiting = [], []
    for c in rollup:
        if c.get("__typename") == "StatusContext":
            name, state = c.get("context", "?"), (c.get("state") or "").upper()
            if state in ("PENDING", "EXPECTED"):
                waiting.append(name)
            elif state != "SUCCESS":
                red.append(f"{name} ({state.lower()})")
            continue
        name = " / ".join(x for x in (c.get("workflowName"), c.get("name")) if x) or "?"
        if (c.get("status") or "").upper() != "COMPLETED":
            waiting.append(name)
        elif (c.get("conclusion") or "").upper() not in GREEN:
            red.append(f"{name} ({(c.get('conclusion') or 'none').lower()})")
    if red:
        return False, "checks failed: " + ", ".join(red)
    if waiting:
        return False, "checks still running: " + ", ".join(waiting)
    return True, ""


def choose(prs, base="main"):
    """The pull requests to merge, in number order, and the ones left out before merging, each with why."""
    chosen, left = [], []
    for pr in sorted(prs, key=lambda p: p["number"]):
        if pr.get("isDraft"):
            left.append((pr, "a draft"))
        elif pr.get("baseRefName") != base:
            left.append((pr, f"based on {pr.get('baseRefName')}, not {base}"))
        else:
            green, why = checks(pr.get("statusCheckRollup") or [])
            if green:
                chosen.append(pr)
            else:
                left.append((pr, why))
    return chosen, left


# ---- the test plan ----------------------------------------------------------------------------------------------------

def is_plan(heading):
    h = re.sub(r"[*_`:]", "", heading).strip().lower()
    return h.startswith(PLAN_HEADINGS)


def how_to_check(body):
    """A body's "how to check": [(heading, lines)] for each plan section in it, in order, else [(None, its first paragraph)]."""
    lines = [l.rstrip() for l in (body or "").replace("\r\n", "\n").split("\n") if not FOOTER.match(l.strip())]
    sections, i = [], 0
    while i < len(lines):
        line = lines[i].strip()
        atx, bold, label = ATX.match(line), BOLD_LINE.match(line), BOLD_LABEL.match(line)
        if atx and is_plan(atx.group(2)):
            level, j = len(atx.group(1)), i + 1
            while j < len(lines) and not ((m := ATX.match(lines[j].strip())) and len(m.group(1)) <= level):
                j += 1
            sections.append((atx.group(2), lines[i + 1:j]))
            i = j
        elif bold and is_plan(bold.group(1)):
            j = i + 1
            while j < len(lines) and not (ATX.match(lines[j].strip()) or BOLD_LINE.match(lines[j].strip())):
                j += 1
            sections.append((bold.group(1).rstrip(":"), lines[i + 1:j]))
            i = j
        elif label and not bold and is_plan(label.group(1)):
            j = i + 1
            while j < len(lines) and lines[j].strip() and not ATX.match(lines[j].strip()):
                j += 1
            sections.append((label.group(1).rstrip(":"), [label.group(2)] + lines[i + 1:j]))
            i = j
        else:
            i += 1
    sections = [(h, trim(ls)) for h, ls in sections if trim(ls)]
    if sections:
        return sections
    paragraph, started = [], False
    for l in lines:
        if not l.strip():
            if started:
                break
            continue
        if ATX.match(l.strip()) or (BOLD_LINE.match(l.strip()) and not started):
            if started:
                break
            continue
        started = True
        paragraph.append(l)
    return [(None, paragraph or ["(no description)"])]


def trim(lines):
    lines = list(lines)
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def plan(base_sha, head_sha, merged, left, run_url=None, now=None, dry=False):
    now = now or datetime.now(timezone.utc)
    t = ["# Tonight's build", ""]
    what = f"main at `{base_sha[:8]}` with {len(merged)} pull request{'s' if len(merged) != 1 else ''} merged on top, in number order"
    t.append(f"{what}: `tonight` at `{head_sha[:8]}`." if not dry else f"{what} (a dry run: nothing merged).")
    t.append(f"Built {now:%Y-%m-%d %H:%M} UTC" + (f" ([the run]({run_url}); the build is its artifact)." if run_url else "."))
    t.append("It's a developer build (note 514). To build it yourself: `git fetch origin tonight && git checkout FETCH_HEAD`.")
    t += ["", "## Merged", ""]
    if not merged:
        t += ["Nothing: tonight's build is main.", ""]
    for pr in merged:
        t.append(f"### #{pr['number']}: {pr['title']}")
        who = (pr.get("author") or {}).get("login")
        t.append(f"{pr['url']} · `{pr.get('headRefName', '')}` at `{pr['headRefOid'][:8]}`" + (f" · {who}" if who else ""))
        t.append("")
        for heading, lines in how_to_check(pr.get("body")):
            t.append(f"**{heading}**" if heading else "_(no \"how to check\" section: its first paragraph)_")
            t += lines + [""]
    t += ["## Left out", ""]
    t += [f"- #{pr['number']}: {pr['title']} ({pr['url']}): {why}" for pr, why in left] or ["Nothing."]
    return "\n".join(t).rstrip() + "\n"


# ---- merging ----------------------------------------------------------------------------------------------------------

def merge(chosen, cwd, base_ref="HEAD", remote="origin"):
    """Merges each chosen pull request onto the checkout, in order. Returns (merged, left out with why)."""
    if not chosen:
        return [], []
    base = run(["git", "rev-parse", base_ref], cwd).stdout.strip()
    refs = [f"+refs/pull/{pr['number']}/head:refs/tonight/pr-{pr['number']}" for pr in chosen]
    run(["git", "fetch", "--quiet", "--no-tags", remote, *refs], cwd)
    ident = ["-c", "user.name=github-actions[bot]", "-c", "user.email=41898283+github-actions[bot]@users.noreply.github.com"]
    merged, left, touched = [], [], {}
    for pr in chosen:
        n = pr["number"]
        sha = run(["git", "rev-parse", f"refs/tonight/pr-{n}"], cwd).stdout.strip()
        if sha != pr["headRefOid"]:
            left.append((pr, f"its head moved to {sha[:8]} since its checks were read (at {pr['headRefOid'][:8]})"))
            continue
        p = run(["git", *ident, "merge", "--no-ff", "--no-edit", "-m", f"Tonight: #{n} {pr['title']}", sha], cwd, check=False)
        if p.returncode == 0:
            merged.append(pr)
            touched[n] = set(run(["git", "diff", "--name-only", f"{base}...{sha}"], cwd).stdout.split())
            continue
        files = run(["git", "diff", "--name-only", "--diff-filter=U"], cwd, check=False).stdout.split()
        run(["git", "merge", "--abort"], cwd, check=False)
        if not files:
            left.append((pr, "doesn't merge: " + (p.stderr.strip() or p.stdout.strip() or "the merge failed").splitlines()[-1]))
            continue
        alone = run(["git", "merge-tree", "--write-tree", "--name-only", "--no-messages", base, sha], cwd, check=False).returncode == 0
        where = ", ".join(files[:6]) + (f" and {len(files) - 6} more" if len(files) > 6 else "")
        if alone:
            with_ = [f"#{m}" for m, fs in touched.items() if fs & set(files)]
            left.append((pr, f"merges onto main alone, but conflicts with {', '.join(with_) or 'the pull requests'} merged before it, in {where}"))
        else:
            left.append((pr, f"conflicts with main in {where or 'its changes'}"))
    return merged, left


# ---- the night ---------------------------------------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "nsmith-gd/darkterritory"))
    ap.add_argument("--base", default="main")
    ap.add_argument("--out", default="out/tonight")
    ap.add_argument("--run", default=None, help="the workflow run's URL, for the plan")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--offline-test", action="store_true")
    a = ap.parse_args()
    if a.offline_test:
        return offline_test()
    prs = read_prs(a.repo, a.base)
    chosen, left = choose(prs, a.base)
    base_sha = run(["git", "rev-parse", "HEAD"]).stdout.strip()
    merged, conflicted = (chosen, []) if a.dry_run else merge(chosen, None)
    left = sorted(left + conflicted, key=lambda x: x[0]["number"])
    head_sha = run(["git", "rev-parse", "HEAD"]).stdout.strip()
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(a.out, "TEST-PLAN.md"), "w") as f:
        f.write(plan(base_sha, head_sha, merged, left, a.run, dry=a.dry_run))
    summary = {
        "base": base_sha, "head": head_sha, "dryRun": a.dry_run,
        "merged": [{"number": p["number"], "title": p["title"], "url": p["url"], "sha": p["headRefOid"]} for p in merged],
        "left": [{"number": p["number"], "title": p["title"], "url": p["url"], "why": why} for p, why in left],
    }
    with open(os.path.join(a.out, "tonight.json"), "w") as f:
        json.dump(summary, f, indent=2)
    print(json.dumps({"merged": [p["number"] for p in merged], "left": {str(p["number"]): why for p, why in left}}, indent=2))
    return 0


# ---- offline ------------------------------------------------------------------------------------------------------------

def offline_test():
    failures = []

    def expect(ok, what):
        print(("ok    " if ok else "FAIL  ") + what)
        if not ok:
            failures.append(what)

    with open(os.path.join(HERE, "fixture.json")) as f:
        fixture = json.load(f)
    prs, want = fixture["prs"], fixture["expect"]
    chosen, left = choose(prs)
    expect([p["number"] for p in chosen] == want["chosen"], f"chosen in number order: {[p['number'] for p in chosen]}")
    whys = {str(p["number"]): why for p, why in left}
    for n, part in want["left"].items():
        expect(part in whys.get(n, ""), f"#{n} left out: {whys.get(n)!r} (wants {part!r})")
    expect(set(whys) == set(want["left"]), f"left out: exactly {sorted(want['left'])}")
    by_number = {str(p["number"]): p for p in prs}
    for n, w in want["plans"].items():
        sections = how_to_check(by_number[n].get("body"))
        text = "\n".join(l for _, ls in sections for l in ls)
        headings = [h for h, _ in sections]
        expect(headings == w["headings"], f"#{n}'s plan from {headings} (wants {w['headings']})")
        for s in w.get("contains", []):
            expect(s in text, f"#{n}'s plan has {s!r}")
        for s in w.get("excludes", []):
            expect(s not in text, f"#{n}'s plan leaves out {s!r}")
    md = plan("a" * 40, "b" * 40, chosen, left, "https://example.invalid/run/1",
              now=datetime(2026, 10, 10, 9, 37, tzinfo=timezone.utc))
    expect(md.startswith("# Tonight's build\n") and "## Left out" in md and "\U0001F916" not in md, "the plan's shape, no footers in it")
    for n in want["chosen"]:
        expect(f"### #{n}: " in md, f"the plan names #{n}")
    offline_merge(expect)
    print(f"\n{len(failures)} failed" if failures else "\nall passed")
    return 1 if failures else 0


def offline_merge(expect):
    """The merging, end to end in a scratch repository: an origin with pull request refs, and a clone of main to merge in."""
    root = tempfile.mkdtemp(prefix="dt-tonight-")
    try:
        origin, work = os.path.join(root, "origin"), os.path.join(root, "work")
        os.makedirs(origin)
        g = lambda *a, cwd=origin: run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false", *a], cwd)

        def commit(name, text, msg):
            with open(os.path.join(origin, name), "w") as f:
                f.write(text)
            g("add", name)
            g("commit", "-q", "-m", msg)
            return g("rev-parse", "HEAD").stdout.strip()

        g("init", "-q", "-b", "main")
        commit("a.txt", "one\ntwo\nthree\n", "start")
        commit("c.txt", "lamp\n", "c")
        heads = {}
        for n, (name, text) in {1: ("b.txt", "new file\n"), 2: ("a.txt", "ONE\ntwo\nthree\n"), 3: ("a.txt", "uno\ntwo\nthree\n"),
                                4: ("c.txt", "lantern\n")}.items():
            g("checkout", "-q", "-b", f"pr{n}", "main")
            heads[n] = commit(name, text, f"pr {n}")
            g("update-ref", f"refs/pull/{n}/head", heads[n])
            g("checkout", "-q", "main")
        # Main moves on under #4: its line is changed on main too.
        commit("c.txt", "headlamp\n", "main changes c")
        heads[5] = heads[1]
        g("update-ref", "refs/pull/5/head", heads[3])  # #5's checks were read on another head: it's moved since
        run(["git", "clone", "-q", origin, work])
        prs = [{"number": n, "title": f"PR {n}", "url": f"https://example.invalid/pull/{n}", "headRefOid": heads[n]} for n in (1, 2, 3, 4, 5)]
        merged, left = merge(prs, work)
        whys = {p["number"]: why for p, why in left}
        expect([p["number"] for p in merged] == [1, 2], f"merged #1 and #2: {[p['number'] for p in merged]}")
        expect("conflicts with #2 merged before it, in a.txt" in whys.get(3, ""), f"#3: {whys.get(3)!r}")
        expect(whys.get(4, "").startswith("conflicts with main in c.txt"), f"#4: {whys.get(4)!r}")
        expect("its head moved" in whys.get(5, ""), f"#5: {whys.get(5)!r}")
        files = run(["git", "show", "HEAD:a.txt"], work).stdout
        expect(files.startswith("ONE"), "the result has #2's change and not #3's")
        expect(run(["git", "status", "--porcelain"], work).stdout.strip() == "", "the checkout is clean after a conflict")
    finally:
        shutil.rmtree(root, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
