using System.Globalization;
using System.Text;

namespace DarkTerritory.Dev.Trends;

/// <summary>
/// The trends as people read them (ARCHITECTURE §8 note 523): the job summary of the Trends workflow (each metric's last values
/// over the commits, and the newest commit's falls), and the comment it leaves on a pull request whose merge made a fall.
/// </summary>
public static class TrendMarkdown
{
    /// <summary>What every comment the workflow leaves ends with.</summary>
    public const string Footer = "---\n_Generated by [Claude Code](https://claude.ai/code)_\n";

    /// <summary>The kinds in the order a summary shows them; perf (some fifty counts) folded away under the rest.</summary>
    static readonly string[] Kinds = ["balance", "pacing", "net", "moments", "sim", "perf"];

    public static string Summary(IReadOnlyList<TrendLine> series, TrendBands bands, int last, string? metric = null)
    {
        var t = new StringBuilder();
        if (series.Count == 0)
            return "### Trends\n\nNo lines yet.\n";
        var newest = series[^1];
        var shown = series.TakeLast(Math.Max(1, last)).ToList();
        int from = series.Count - shown.Count;
        var steps = TrendSeries.Steps(series, bands, from, metric).ToDictionary(s => (s.Line.Commit, s.Metric));
        t.Append(CultureInfo.InvariantCulture, $"### Trends: main at `{newest.Short}`{(newest.Pr is { } pr ? $" (#{pr})" : "")}\n\n");
        t.Append(Nights(newest)).Append(CultureInfo.InvariantCulture,
            $" {(shown.Count == 1 ? "The one commit measured" : $"The last {shown.Count} commits measured, oldest first")}; **bold**: a fall, past its band the bad way from the median of the commits before it; _italic_: a rise; +: measured with changes of its own (a local run).\n\n");
        var falls = steps.Values.Where(s => s.Fall && s.Line.Commit == newest.Commit).ToList();
        if (falls.Count == 0)
            t.Append("No falls at this commit.\n\n");
        else
        {
            t.Append("**Falls at this commit:**\n");
            foreach (var f in falls)
                t.Append(CultureInfo.InvariantCulture, $"- `{f.Metric}`: {Num(f.Value)}, from {Num(f.Level)} (band ±{Num(f.Width)}, worse {Way(f.Bad)})\n");
            t.Append('\n');
        }
        var names = shown.SelectMany(l => l.Metrics.Keys).Distinct().Where(n => metric is null || n == metric).Order(StringComparer.Ordinal).ToList();
        foreach (string kind in Kinds.Concat(names.Select(Kind).Where(k => !Kinds.Contains(k)).Distinct()))
        {
            var rows = names.Where(n => Kind(n) == kind).ToList();
            if (rows.Count == 0)
                continue;
            bool fold = kind == "perf";
            t.Append(fold ? $"<details><summary>{kind} ({rows.Count})</summary>\n\n" : $"**{kind}**\n\n");
            t.Append("| metric | worse | ").AppendJoin(" | ", shown.Select(l => $"`{l.Short[..Math.Min(7, l.Short.Length)]}`{(l.Dirty ? "+" : "")}")).Append(" |\n");
            t.Append("|---|---|").AppendJoin("", shown.Select(_ => "---:|")).Append('\n');
            foreach (string name in rows)
            {
                t.Append(CultureInfo.InvariantCulture, $"| `{name}` | {Way(bands.For(name).Bad)} | ");
                t.AppendJoin(" | ", shown.Select(l => !l.Metrics.TryGetValue(name, out double v) ? ""
                    : steps.TryGetValue((l.Commit, name), out var s) ? s.Fall ? $"**{Num(v)}**" : $"_{Num(v)}_"
                    : Num(v)));
                t.Append(" |\n");
            }
            t.Append(fold ? "\n</details>\n\n" : "\n");
        }
        return t.ToString();
    }

    /// <summary>
    /// The pull request comment for the newest line's falls, or null with none: the numbers, what the nights were, and the
    /// bisect to run if the fall came from more than the one commit.
    /// </summary>
    public static string? Comment(IReadOnlyList<TrendLine> series, TrendBands bands, string? run = null)
    {
        if (series.Count == 0)
            return null;
        var newest = series[^1];
        var falls = TrendSeries.Steps(series, bands, series.Count - 1).Where(s => s.Fall).ToList();
        if (falls.Count == 0)
            return null;
        var t = new StringBuilder();
        string measured = run is { Length: > 0 } ? $" ([the Trends run]({run}))" : "";
        t.Append(CultureInfo.InvariantCulture,
            $"**Trends: {(falls.Count == 1 ? "a metric" : $"{falls.Count} metrics")} fell past {(falls.Count == 1 ? "its band" : "their bands")} on main at `{newest.Short}`**, this pull request's merge{measured}.\n\n");
        t.Append("| metric | worse | before (median) | last measured | this commit | band | each seed |\n|---|---|---:|---:|---:|---:|---|\n");
        foreach (var f in falls)
            t.Append(CultureInfo.InvariantCulture,
                $"| `{f.Metric}` | {Way(f.Bad)} | {Num(f.Level)} | {Num(f.PreviousValue)} (`{f.Previous.Short}`) | **{Num(f.Value)}** | ±{Num(f.Width)} | {string.Join(' ', f.Seeds.Select(Num))} |\n");
        var first = falls[0];
        t.Append('\n').Append(Nights(newest)).Append(" Each night is deterministic, so any one of them can be run again to look: `dt harness ")
            .Append(newest.Options.Harness).Append(" --seed N --trace night.txt`. A bot night moves with any change to the sim, so this asks a question of the change; it isn't a verdict on it.\n\n");
        t.Append("If more than this merge's commit lies between the two (the trends wait one run at a time, and a busy hour's runs are skipped), ")
            .Append(CultureInfo.InvariantCulture, $"`tools/trends/bisect.sh --metric {first.Metric} --good {first.Previous.Short} --bad {newest.Short}` finds the commit.\n\n");
        t.Append(Footer);
        return t.ToString();
    }

    static string Nights(TrendLine line) =>
        string.Create(CultureInfo.InvariantCulture,
            $"{line.Options.Seeds.Count} nights a commit, `dt harness {line.Options.Harness}`, seeds {TrendNights.Range(line.Options.Seeds)}{(line.Options.Perf ? ", and `dt perf`" : "")}.");

    static string Kind(string metric) => metric.Split('.')[0];

    static string Way(Worse bad) => bad switch
    {
        Worse.Up => "up",
        Worse.Down => "down",
        Worse.Either => "either",
        _ => "",
    };

    public static string Num(double v) =>
        Math.Abs(v) >= 1000 ? v.ToString("N0", CultureInfo.InvariantCulture) : v.ToString("0.###", CultureInfo.InvariantCulture);
}
