<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dt</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DarkTerritory.Game/DarkTerritory.Game.csproj" />
    <ProjectReference Include="../DarkTerritory.Editor/DarkTerritory.Editor.csproj" />
    <ProjectReference Include="../DarkTerritory.Dev/DarkTerritory.Dev.csproj" />
  </ItemGroup>
</Project>
